name: deploy
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: srepollock/gatsby-gh-pages-action@5517c70e1cb6588f9b158fed64b48f95f2d439c4
        with:
          access-token: ${{ secrets.KMP }}
          deploy-branch: master
